### ISSUE TITLE
Black and python version mismatch

### ISSUE THREAD

**Issue by sanders41** [long2ice/meilisync-admin#1]
In the `pyproject.toml` the minimum python version is set to 3.11, but the black target versions are `target-version = ['py37', 'py38', 'py39', 'py310']`. 

I'm assuming either target versions should be `target-version = ['py38', 'py39', 'py310', 'py311']` and python should be `python = "^3.8"` (I would recommend dropping 3.7 since it is EOL), or if the python version is correct at 3.11 the target version should be `target-version = ['py311']`.

**Comment by long2ice** [comment]
That's right.
