### ISSUE TITLE
Navbar hover menu hard to read in dark mode

### ISSUE THREAD

**Issue by sanders41** [long2ice/meilisync-admin#3]
When in dark mode the user hover menu background font stays black making it hard to read.

![meilisync](https://github.com/long2ice/meilisync-admin/assets/25045024/03f73bc0-aa27-4eab-9b61-2a0fbe2c211e)

**Comment by sanders41** [comment]
After looking at the Dockerfile this maybe should be moved to long2ice/meilisync-web?

**Comment by long2ice** [comment]
YES

**Comment by sanders41** [comment]
Moved to `meilisync-web` https://github.com/long2ice/meilisync-web/issues/1
