### ISSUE TITLE
Missing content-type

### ISSUE THREAD

**Issue by ThangBuiDuc** [long2ice/meilisync-admin#5]
while i create a sync task and throw an error like meilisearch_python_sdk.errors.MeilisearchApiError: MeilisearchApiError.missing_content_type Error message: A Content-Type header is missing. Accepted values for the Content-Type header are: `application/json` invalid_request Error documentation: https://docs.meilisearch.com/errors#missing_content_type

**Comment by long2ice** [comment]
Show the error stack

**Comment by ThangBuiDuc** [comment]
> Show the error stack

![image](https://github.com/long2ice/meilisync-admin/assets/111365153/0a99b8db-7610-4b15-b9d3-99af7206524d)

**Comment by long2ice** [comment]
What's your meilisearch version?

**Comment by long2ice** [comment]
I never see that

**Comment by ThangBuiDuc** [comment]
im using meilisearch v1.4.0

**Comment by long2ice** [comment]
Try latest

**Comment by ThangBuiDuc** [comment]
> Try latest

its worked. Thank you. But i got another error when i full refresh task: TypeError: meilisync.progress.redis.Redis.set() argument after ** must be a mapping, not str
![image](https://github.com/long2ice/meilisync-admin/assets/111365153/45f0418b-9d77-4c68-869b-721992f1b7b2)

**Comment by long2ice** [comment]
What's your db?

**Comment by ThangBuiDuc** [comment]
mine is postgres 14

**Comment by long2ice** [comment]
Just try again

**Comment by ThangBuiDuc** [comment]
Another error!
![image](https://github.com/long2ice/meilisync-admin/assets/111365153/6025134b-55f0-4c00-b83a-2d768b2c6ae1)

**Comment by long2ice** [comment]
Just try again

**Comment by ThangBuiDuc** [comment]
> Just try again

Another error: type date is not JSON serializable
![image](https://github.com/long2ice/meilisync-admin/assets/111365153/d3c195b6-4149-4b43-9f65-366bc06ab251)

**Comment by long2ice** [comment]
Just try again

**Comment by ThangBuiDuc** [comment]
all worked. Thank you very much, u help me a lot.
